name: fastq-pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastqc
  - fastp
  - trim-galore
  - bwa
  - samtools
  - bcftools
  - bedtools
  - spades
  - minimap2
  - sra-tools
  - matplotlib
  - python=3.10